name: Build & Deploy
on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: seda
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{ secrets.HOST }}
          key: ${{ secrets.SSHKEY }} 
          username: ${{ secrets.USERNAME }}
     
          script: |
            mkdir app
            cd app 
            git@github.com:Shock55/CAS-Data-Engineering.git
            echo 'Deployment successful to digital ocean' 
